#
#  pyEfi tmuxp dashboard
#
session_name: pyEfiDashboard
#suppress_history: false
windows:
- window_name: example
  layout: main-vertical
  options:
    main-pane-width: 110
  panes:
# 1: run redis data display
# '--iniFile=' needed to encode/decode serial data, not needed for stimulator/generic data
#    - ./pyefi.py run dashboard --channelKey=test --confKey=rpm --iniFile=microsquirt.ini
    - ./pyefi.py run dashboard --channelKey=test --confKey=rpm

# 2: run collection
#    - ./pyefi.py run collectMS --iniFile=microsquirt.ini --serialLoc=/dev/ttyS0 --channelKey=test
    - ./pyefi.py run stim --channelKey=test

# 3: process incoming collected data -- 'label, gfx, min, max, width/just'
#    - ./pyefi.py run dashboard --channelKey=test --confKey=health --iniFile=microsquirt.ini
    - ./pyefi.py run dashboard --channelKey=test --confKey=health

# 4: sync dashboard yml config loads 'dashboards.yml' by default can take '--ymlFileName=' argument
    - ./pyefi.py dash syncYml dashboards.yml
